export const PRODUCTS = [
  {
    id: "hgd", name: "JWT HydroGuard-D",
    subtitle: "Diaphragm Hydronic Expansion Tank",
    desc: "A fixed-diaphragm expansion tank for closed-loop hydronic heating and chilled water systems. A permanently sealed Butyl/EPDM membrane separates the pre-charged air cushion from system water, preventing waterlogging and air absorption. The diaphragm is factory-installed and does not require replacement — with precharge and membrane condition checked according to the supplier maintenance instructions.",
    examples: "Office buildings & schools with hot water baseboard or fan-coil heating · Chilled water loops for rooftop air handlers · Radiant floor heating systems in warehouses · Campus central plant distribution loops · Closed-loop snow-melt systems",
    prefix: "JWT-HGD", maxTemp: 240, potable: false, internals: "diaphragm",
    mawpOptions: [100, 125, 150, 175, 250, 300], defaultMawp: 150,
    precharge: 12, color: "#C0392B",
    howItWorks: `The fixed diaphragm separates water from the precharged gas. Expanding water compresses the gas cushion. Usable acceptance is limited by both operating pressures and the supplier membrane rating.\n\nSet precharge with the water side depressurized, using the approved system pressure basis. The diaphragm attachment, assembly sequence and heat protection require the supplier design. Inspect and maintain the tank according to its instructions.`,
  },
  {
    id: "hgfb", name: "JWT HydroGuard-FB",
    subtitle: "Full-Acceptance Bladder Expansion Tank",
    desc: "A large-capacity expansion tank with a field-replaceable Butyl rubber bladder that occupies the full internal volume. The full-acceptance design maximizes available water acceptance capacity for a given tank size. Designed for large commercial and institutional hydronic systems where decades of service life and easy bladder replacement are essential — no need to replace the entire ASME vessel when the bladder eventually wears.",
    examples: "Hospital campus heating plants (500+ gallon systems) · High-rise hot water distribution · University central heating plants · District energy systems · Large industrial process cooling loops · Data center chilled water systems",
    prefix: "JWT-HGFB", maxTemp: 240, potable: false, internals: "full-bladder",
    mawpOptions: [100, 125, 150, 175, 250, 300], defaultMawp: 150,
    precharge: 12, color: "#2980B9",
    howItWorks: `The replaceable bladder separates water inside the bladder from the surrounding gas. Full acceptance describes the membrane volume capability. Actual operating acceptance remains limited by the pressure range and precharge.\n\nUse a matched bladder, access closure, seals and water connection. The access opening and installation procedure must come from the supplier assembly drawing. Isolate and depressurize both sides before service. Use the approved bolting procedure and rated air-charge valve.`,
  },
  {
    id: "hgrb", name: "JWT HydroGuard-RB",
    subtitle: "Partial-Acceptance Bladder Expansion Tank",
    desc: "A compact expansion tank with a field-replaceable Butyl rubber bladder that occupies a portion of the internal volume. The supplier maximum water acceptance is lower than the vessel nominal volume. Both pressure acceptance and membrane capacity must be checked. Ideal for mid-size commercial systems where bladder replaceability is desired but full-acceptance capacity is not needed.",
    examples: "Medium office buildings (100–500 gallon systems) · Retail and restaurant hydronic heating · Multi-family residential boiler rooms · Small industrial process heating · Church and community center heating systems · Gymnasium and recreation facility HVAC",
    prefix: "JWT-HGRB", maxTemp: 240, potable: false, internals: "partial-bladder",
    mawpOptions: [100, 125, 150, 175, 250, 300], defaultMawp: 150,
    precharge: 12, color: "#8E44AD",
    howItWorks: `The replaceable bladder has a supplier-rated maximum water volume smaller than the vessel nominal volume. Sizing must satisfy both this limit and gas compression between minimum and maximum operating pressure. Partial acceptance does not itself reduce the required vessel volume.\n\nUse the supplier matched bladder, support arrangement, access closure and water connection. The support pipe and access size are not inferred from vessel diameter. Isolate and depressurize both sides before service.`,
  },
  {
    id: "as", name: "JWT AquaShield",
    subtitle: "Thermal Expansion Tank — Potable Water",
    desc: "Protects domestic hot water systems from dangerous pressure spikes caused by thermal expansion in closed plumbing systems. Required by code whenever a backflow preventer (BFP), check valve, or pressure reducing valve (PRV) is installed on the cold water supply — which is virtually every modern building. Without this tank, heated water has nowhere to expand, causing relief valve dripping, premature water heater failure, and potential pipe damage. Potable service requires documented certification of all wetted components for the supplied assembly.",
    examples: "Hotels and dormitories with central water heaters · Commercial kitchens and restaurants · Apartment buildings with master BFP · Hospitals and healthcare facilities · Schools with domestic hot water recirculation · Any building where code requires a backflow preventer on the water main",
    prefix: "JWT-AS", maxTemp: 200, potable: true, internals: "diaphragm",
    mawpOptions: [100, 125, 150], defaultMawp: 150,
    precharge: 55, color: "#27AE60",
    howItWorks: `In a closed potable-water system, thermal expansion increases pressure unless the expansion is accommodated. The diaphragm separates potable water from precharged gas.\n\nUse the actual heated volume, minimum and maximum water temperatures, supply pressure and available pressure margin. Set the empty-tank precharge to the approved pressure basis. Follow the manufacturer piping instructions and verify potable certification for the actual wetted assembly.`,
  },
  {
    id: "cv", name: "JWT ChillVault",
    subtitle: "Chilled Water Buffer Tank",
    desc: "A plain ASME pressure vessel that adds thermal mass (water volume) to chilled water loops. When the system water volume is too small relative to the chiller's capacity, the compressor reaches setpoint too quickly and short-cycles — turning on and off every few minutes. This destroys compressor contactors, wastes energy, and shortens equipment life. The ChillVault adds enough water volume to extend run times to manufacturer-recommended minimums. No internal bladder or diaphragm — this is purely a volume vessel. A separate HydroGuard expansion tank is still required in the system for pressure control.",
    examples: "Office building with VRF-to-water chiller and low system volume · Data centers with precision cooling and tight temperature control · Medical imaging suites (MRI cooling) · Brewery and winery glycol chiller loops · Pharmaceutical clean rooms · Retrofit projects where existing piping volume is too low for new high-efficiency chillers",
    prefix: "JWT-CV", maxTemp: 450, potable: false, internals: "none",
    mawpOptions: [100, 125, 150, 175, 250], defaultMawp: 150,
    precharge: 0, color: "#2C3E50",
    howItWorks: `The chilled-water buffer adds active thermal mass to reduce source cycling. It has no bladder and does not provide expansion-pressure control.\n\nUse the minimum stable cooling output, coincident load, minimum run time, tank control deadband and existing active system volume. A fully mixed cycling calculation does not establish mission-critical ride-through duration or stratification performance. Piping and controls must make the credited water volume available during the controlling cycle.`,
  },
  {
    id: "hv", name: "JWT HeatVault",
    subtitle: "Hot Water Buffer Tank",
    desc: "A plain ASME pressure vessel that adds thermal mass to closed-loop hot water heating systems. Modern high-efficiency modulating and condensing boilers are prone to short-cycling during mild weather and low-load conditions — the building only needs a fraction of the boiler's output, so it fires briefly and shuts down, over and over. This wastes fuel, reduces condensing efficiency, and causes thermal fatigue. The HeatVault absorbs excess heat and extends boiler run times, allowing the burner to operate in its efficient steady-state range. No bladder or diaphragm — a separate HydroGuard expansion tank is still needed for pressurization.",
    examples: "Schools and churches with oversized boilers and intermittent occupancy · Multi-boiler cascade systems where the lead boiler needs extended run time · Retrofit projects replacing atmospheric boilers with modulating condensing units · Radiant floor heating with high thermal lag · Industrial process heating with variable demand · Snow-melt systems with intermittent operation",
    prefix: "JWT-HV", maxTemp: 450, potable: false, internals: "none",
    mawpOptions: [100, 125, 150, 175, 250], defaultMawp: 150,
    precharge: 0, color: "#D35400",
    howItWorks: `The hot-water buffer absorbs surplus heat when source output exceeds the coincident load. It has no bladder and requires separate system expansion-pressure control.\n\nUse the minimum stable output of the controlling boiler stage, minimum coincident load, run time and tank control deadband. Deduct only existing volume that participates in that cycle. Hydraulic separation, inlet diffusion and controls require the approved piping design.`,
  },
];

